server:
    port: 9001

spring:
  application:
    name: USER-SERVICE

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8787/eureka
    instance:
      hostname: localhost
